# File: .github/workflows/repo-sync.yml
name: sync-573462273-scripts
on:
  schedule:
    - cron: '1 0,15/3 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-573462273-Unicom
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11      
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync 573462273-Unicom-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/DJ-clamp/BaseSation.git"
          source_branch: "azmodan"
          destination_branch: "dev"
          github_token: ${{ secrets.PAT }}
